 
-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;



package slv16_a_pack is 
  type slv16_a is array (natural range <>) of std_logic_vector(15 downto 0);
end slv16_a_pack;

package body slv16_a_pack is

end slv16_a_pack;
