-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;
use work.slv32_a_pack.all;


entity ramBlock is 
  port(
    ReadAddr :  in  std_logic_vector(31 downto 0) := (others => '0');
    ReadData :  out  std_logic_vector(31 downto 0) := (others => '0');
    clk :  in  std_logic := '0';
    wAddr :  in  std_logic_vector(31 downto 0) := (others => '0');
    wData :  in  std_logic_vector(31 downto 0) := (others => '0');
    we :  in  std_logic := '0'
  );
end entity;



architecture rtl of ramBlock is

--------------------------ramBlock-----------------
  signal content : slv32_a(100 - 1 downto 0)  := (others => (others => '0'));
-------------------------- end ramBlock-----------------

begin
  -- begin architecture
  
-----------------------------------
proc : process(clk) is
  begin
    if rising_edge(clk) then 
  
      if (we = '1') then 
        content(to_integer(signed( wAddr))) <= wData;
        
      end if;
    ReadData <= content(to_integer(signed( ReadAddr)));
    end if;
  
  end process;
  -- end architecture

end architecture;