 
-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;



package slv32_a_pack is 
  type slv32_a is array (natural range <>) of std_logic_vector(31 downto 0);
end slv32_a_pack;

package body slv32_a_pack is

end slv32_a_pack;
