-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.argg_hdl_core.all;
use work.axisStream_slv32.all;


entity axFilter1 is 
  port(
    DataIn_s2m :  out  axiStream_slv32_s2m := axiStream_slv32_s2m_null;
    DataIn_m2s :  in  axiStream_slv32_m2s := axiStream_slv32_m2s_null;
    clk :  in  std_logic := '0'
  );
end entity;



architecture rtl of axFilter1 is

--------------------------axFilter1-----------------
-------------------------- end axFilter1-----------------

begin
  -- begin architecture
  -- end architecture

end architecture;