-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;


package xgen_rollingCounter is 

-------------------------------------------------------------------------
------- Start Psuedo Class rollingCounter -------------------------

type rollingCounter is record 
  Counter : integer; 
end record;


constant rollingCounter_null : rollingCounter:= (
  Counter => 0
);


type rollingCounter_a is array (natural range <>) of rollingCounter;

-- empty procedure removed. name: 'push'
-- empty procedure removed. name: 'pull'
  procedure reset (self : inout rollingCounter);
  procedure incr (self : inout rollingCounter; MaxCount :  in  integer);
------- End Psuedo Class rollingCounter -------------------------
-------------------------------------------------------------------------


end xgen_rollingCounter;


package body xgen_rollingCounter is

-------------------------------------------------------------------------
------- Start Psuedo Class rollingCounter -------------------------
-- empty procedure removed. name: 'push'
-- empty procedure removed. name: 'pull'
procedure reset ( self : inout rollingCounter) is
   
  begin 
 self.Counter := 0;
   
end procedure;

procedure incr ( self : inout rollingCounter; MaxCount :  in  integer) is
   
  begin 
 self.Counter := self.Counter + 1;
  
    if (self.Counter = MaxCount) then 
      self.Counter := 0;
      
    end if;
   
end procedure;

------- End Psuedo Class rollingCounter -------------------------
  -------------------------------------------------------------------------


end xgen_rollingCounter;